export const weeks = [
 {n:1,title:'Archaeological thinking & human origins',topic:'Introduction to Archaeology',region:'Methods, human origins & early communities',sites:'Dmanisi · Göbekli Tepe · Tikal',intro:'Identify material evidence, distinguish observation from interpretation, and place early human communities in context.',prompts:['What can stratigraphy tell us about relative chronology?','How is archaeology different from palaeontology?']},
 {n:2,title:'Urbanization',topic:'Urbanization',region:'Mediterranean & Southwest Asia',sites:'Uruk · Tel-Abada · Saqqara',intro:'Use settlement, production, writing and monument evidence to understand urban life.',prompts:['What evidence supports identifying Uruk as a city?','Compare a ziggurat and a pyramid by function and setting.']},
 {n:3,title:'Social hierarchy',topic:'Social Hierarchy',region:'Indus civilization & early China',sites:'Mohenjo-daro · Harappa · Erlitou · Yinxu',intro:'Compare cities, households, burials and production without confusing interpretation with direct evidence.',prompts:['Compare city planning at Mohenjo-daro and Erlitou.','Why does the name Priest-King not prove a ruling class existed?']},
 {n:4,title:'Interacting with the Environment',topic:'Interacting with the Environment',region:'Maya and Inca worlds',sites:'Maya · Inca',intro:'Explore environmental adaptation, engineered landscapes and the interpretation of change.',prompts:['How did Maya communities interact with their environment?','What evidence does Lecture 4 use to discuss environmental adaptation?']},
 {n:5,title:'Visual Power',topic:'Visual Power',region:'Art, representation and authority',sites:'Images · monuments · visual culture',intro:'Use visual evidence to distinguish observation, meaning and interpretation.',prompts:['How can visual representation communicate power?','Compare two examples of visual authority in Lecture 5.']},
 {n:6,title:'Food Culture and Hong Kong Archaeology',topic:'Food Culture and Hong Kong Archaeology',region:'Diet and everyday life',sites:'Hong Kong · foodways',intro:'Study the supplied readings on food culture and archaeological evidence.',prompts:['What evidence helps archaeologists reconstruct diet?','What does the seafood reading tell us about ancient Hong Kong?']},
 {n:7,title:'Violence',topic:'Violence',region:'Evidence and representation',sites:'Archaeological interpretation · Vikings',intro:'Examine the supplied readings and distinguish representations from archaeological evidence.',prompts:['How are Vikings represented in the assigned reading?','How should representations be checked against archaeological evidence?']},
];
