export type StudyExportItem={question:string;answer:string;sources:{title:string;label:string;docId:string;page:number}[];image?:{src:string}};
export function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
const safeImage=(src:string)=>/^data:image\/(?:webp|png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(src)?src:'';
export function studySheet(title:string,items:StudyExportItem[],images:Record<string,string>,answers=true){
 const h=escapeHtml;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)}</title><style>body{font:16px/1.65 system-ui,sans-serif;max-width:850px;margin:40px auto;padding:0 24px;color:#17291d;background:white}h1{line-height:1.2}h2{font-size:22px}article{border-top:1px solid #bcc8bd;padding:20px 0;break-inside:avoid}img{display:block;max-width:100%;max-height:430px;margin:18px auto;object-fit:contain}.space{height:90px;border-bottom:1px solid #d5dcd5}small,header p{color:#536052}.answer-key{break-before:page;margin-top:50px}.answer{white-space:pre-wrap}@media print{body{margin:0;max-width:none;font-size:12pt}.instructions{display:none}img{max-height:95mm}a{color:inherit}}</style></head><body><header><h1>${h(title)}</h1><p>${items.length} questions · ARCL1001 revision · Unofficial practice</p><p class="instructions">This file works offline, including its question images. Use your browser’s Print command to print it or save as PDF.${answers?' Model answers are in a separate section below.':''}</p></header><h2>Questions</h2>${items.map((q,i)=>`<article><h3>${i+1}. ${h(q.question)}</h3>${q.image&&safeImage(images[q.image.src]||'')?`<img src="${safeImage(images[q.image.src])}" alt="Question ${i+1} image">`:''}<div class="space"></div></article>`).join('')}${answers?`<section class="answer-key"><h2>Model answers &amp; sources</h2>${items.map((q,i)=>`<article><h3>${i+1}. ${h(q.question)}</h3><p class="answer">${h(q.answer)}</p>${q.sources.map(s=>`<p><small>${h(s.title)} · ${h(s.label)}</small><br><a href="https://arcl1001-study-boscofungg.vercel.app/?doc=${encodeURIComponent(s.docId)}&amp;page=${s.page}">View cited course page online</a></p>`).join('')}</article>`).join('')}</section>`:''}</body></html>`;
}
export function studyCsv(items:StudyExportItem[],answers=true){
 const cell=(s:string)=>'"'+(/^[\s]*[=+\-@]/.test(s)?"'"+s:s).replace(/"/g,'""')+'"';
 return '\ufeff'+[['Question',...(answers?['Model answer']:[]),'Sources','Question image (online)'],...items.map(q=>[q.question,...(answers?[q.answer]:[]),q.sources.map(s=>`${s.title} · ${s.label}`).join('; '),q.image?`https://arcl1001-study-boscofungg.vercel.app${q.image.src}`:''])].map(row=>row.map(cell).join(',')).join('\r\n');
}
